export enum ROOT_ROUTES {
  AUTH_NAVIGATION = 'AUTH_NAVIGATION',
  APP_NAVIGATION = 'APP_NAVIGATION',
}

export enum AUTH_NAVIGATION {
  LOGIN = '[AUTH] LOGIN',
}

export enum APP_NAVIGATION {
  HOME = '[APP] HOME',
  SEARCH = '[APP] SEARCH',
  CREATE = '[APP] CREATE',
  NOTIFICATION = '[APP] NOTIFICATION',
  PROFILE = '[APP] PROFILE',
  COMMENT = '[APP] COMMENT',
  CHAT = '[APP] CHAT',
  MEDIA = '[APP] MEDIA',
}

export enum HOME_NAVIGATION {
  NEW_FEED = '[HOME] NEW_FEED',
}
